---
- name: mds - fail if required variables are unset
  ansible.builtin.fail:
    msg: "proxmox_ceph_mds must be a non-empty list, and each item needs a 'node' key."
  when: proxmox_ceph_mds | length == 0

- name: mds - create/delete Ceph metadata servers
  community.proxmox.proxmox_ceph_mds:
    api_host:         "{{ proxmox_ceph_api_host }}"
    api_user:         "{{ proxmox_ceph_api_user }}"
    api_password:     "{{ proxmox_ceph_api_password }}"
    api_token_id:     "{{ proxmox_ceph_api_token_id }}"
    api_token_secret: "{{ proxmox_ceph_api_token_secret }}"
    validate_certs:   "{{ proxmox_ceph_validate_certs }}"
    node:  "{{ item.node }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ proxmox_ceph_mds }}"
  loop_control:
    label: "{{ item.node }}"
  delegate_to: localhost
