galaxy_info:
  author: mgcdrd
  description: looks for a group all hosts are a part of and adds all host in any group to the /etc/hosts on all hosts.

  #issue_tracker_url: http://example.com/issue/tracker

  license: GPL-3.0-or-later

  min_ansible_version: "2.14"

  platforms:
  - name: EL
    versions:
    - '8'
    - '9'
  - name: Debian
    versions:
    - bullseye
  
  galaxy_tags: 
  - mgcdrd

#dependencies: []
