galaxy_info:
  author: mgcdrd
  description: >-
    Populates /etc/hosts with the IPs and hostnames of a cluster group.
    Designed for Kubernetes, HAProxy, Galera, and similar cluster deployments.

  license: GPL-3.0-or-later

  min_ansible_version: "2.14"

  platforms:
    - name: EL
      versions:
        - '9'
        - '10'
    - name: Debian
      versions:
        - bookworm
        - trixie

  galaxy_tags:
    - mgcdrd
    - hosts
    - cluster
