---

- name: aide main - install
  ansible.builtin.import_tasks: install.yml

- name: aide main - configure
  ansible.builtin.import_tasks: configure.yml

- name: aide main - initialise database
  ansible.builtin.import_tasks: init.yml

- name: aide main - schedule
  ansible.builtin.import_tasks: schedule.yml
