---
galaxy_info:
  author: mgcdrd
  description: Create a ProxMox VE cluster and join additional nodes to it via the PVE API
  role_name: proxmox_cluster

  license: GPL-3.0-or-later
  min_ansible_version: '2.14'

  galaxy_tags:
    - mgcdrd

collections:
  - community.proxmox
