---

- name: login_banner main - Deploy login banners
  ansible.builtin.template:
    src:   banner.j2
    dest:  "{{ item }}"
    owner: root
    group: root
    mode:  "0644"
  loop:
    - /etc/issue
    - /etc/issue.net
