---
- name: info - list configured storage
  community.proxmox.proxmox_storage_info:
    api_host:         "{{ proxmox_storage_api_host }}"
    api_user:         "{{ proxmox_storage_api_user }}"
    api_password:     "{{ proxmox_storage_api_password }}"
    api_token_id:     "{{ proxmox_storage_api_token_id }}"
    api_token_secret: "{{ proxmox_storage_api_token_secret }}"
    validate_certs:   "{{ proxmox_storage_validate_certs }}"
  register: proxmox_storage_facts
  delegate_to: localhost
