---
- name: info - query cluster status
  community.proxmox.proxmox_cluster_status_info:
    api_host:         "{{ proxmox_cluster_api_host }}"
    api_user:         "{{ proxmox_cluster_api_user }}"
    api_password:     "{{ proxmox_cluster_api_password }}"
    api_token_id:     "{{ proxmox_cluster_api_token_id }}"
    api_token_secret: "{{ proxmox_cluster_api_token_secret }}"
    validate_certs:   "{{ proxmox_cluster_validate_certs }}"
  register: proxmox_cluster_status
  delegate_to: localhost

- name: info - query cluster join info (fingerprint/nodelist)
  community.proxmox.proxmox_cluster_join_info:
    api_host:         "{{ proxmox_cluster_api_host }}"
    api_user:         "{{ proxmox_cluster_api_user }}"
    api_password:     "{{ proxmox_cluster_api_password }}"
    api_token_id:     "{{ proxmox_cluster_api_token_id }}"
    api_token_secret: "{{ proxmox_cluster_api_token_secret }}"
    validate_certs:   "{{ proxmox_cluster_validate_certs }}"
  register: proxmox_cluster_join_facts
  delegate_to: localhost
