---
- name: nic - configure VM network interface
  community.proxmox.proxmox_nic:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    vmid:      "{{ proxmox_nic_vmid | default(_proxmox_nic_vmid, true) }}"
    interface: "{{ nic_item.interface }}"
    bridge:    "{{ nic_item.bridge | default(omit, true) }}"
    model:     "{{ nic_item.model | default('virtio') }}"
    tag:       "{{ nic_item.tag | default(omit, true) }}"
    firewall:  "{{ nic_item.firewall | default(omit, true) }}"
    mtu:       "{{ nic_item.mtu | default(omit, true) }}"
    mac:       "{{ nic_item.mac | default(omit, true) }}"
    state:     "{{ nic_item.state | default('present') }}"
  loop: "{{ proxmox_nic_interfaces }}"
  loop_control:
    loop_var: nic_item
    label: "{{ nic_item.interface }} ({{ nic_item.state | default('present') }})"
  delegate_to: localhost
