---
- name: lifecycle - fail if required variables are unset
  ansible.builtin.fail:
    msg: "proxmox_vm_target_name and proxmox_vm_lifecycle_state (started|stopped|absent) are required."
  when: >
    not proxmox_vm_target_name or
    proxmox_vm_lifecycle_state not in ['started', 'stopped', 'absent']

- name: lifecycle - discover target VM
  ansible.builtin.include_tasks: discover.yml
  vars:
    proxmox_vm_discover_name: "{{ proxmox_vm_target_name }}"

- name: lifecycle - set VM state
  community.proxmox.proxmox_kvm:
    api_host:         "{{ proxmox_vm_api_host }}"
    api_user:         "{{ proxmox_vm_api_user }}"
    api_password:     "{{ proxmox_vm_api_password }}"
    api_token_id:     "{{ proxmox_vm_api_token_id }}"
    api_token_secret: "{{ proxmox_vm_api_token_secret }}"
    validate_certs:   "{{ proxmox_vm_validate_certs }}"
    vmid:  "{{ proxmox_vm_discovered_vmid }}"
    node:  "{{ proxmox_vm_discovered_node }}"
    state: "{{ proxmox_vm_lifecycle_state }}"
    force: "{{ proxmox_vm_force_stop if proxmox_vm_lifecycle_state == 'stopped' else omit }}"
    destroy_unreferenced_disks: "{{ proxmox_vm_destroy_unreferenced_disks if proxmox_vm_lifecycle_state == 'absent' else omit }}"
    timeout: "{{ proxmox_vm_lifecycle_timeout }}"
  delegate_to: localhost
