---
- name: config - fail if required variable is unset
  ansible.builtin.fail:
    msg: "proxmox_node_config_target is required."
  when: not proxmox_node_config_target

- name: config - update node certificates/DNS/subscription
  community.proxmox.proxmox_node:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password }}"
    api_token_id:     "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    node_name:     "{{ proxmox_node_config_target }}"
    certificates:  "{{ proxmox_node_certificates | default(omit, true) }}"
    dns:           "{{ proxmox_node_dns | default(omit, true) }}"
    subscription:  "{{ proxmox_node_subscription | default(omit, true) }}"
  delegate_to: localhost
