---
- name: info - list nodes with detailed status
  community.proxmox.proxmox_node_info:
    api_host:         "{{ proxmox_node_api_host }}"
    api_user:         "{{ proxmox_node_api_user }}"
    api_password:     "{{ proxmox_node_api_password }}"
    api_token_id:     "{{ proxmox_node_api_token_id }}"
    api_token_secret: "{{ proxmox_node_api_token_secret }}"
    validate_certs:   "{{ proxmox_node_validate_certs }}"
  register: proxmox_node_facts
  delegate_to: localhost
