---
galaxy_info:
  role_name: kernel_modules
  author: mgcdrd
  description: Load and persist kernel modules via modprobe
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: EL
      versions:
        - '9'
        - '10'
dependencies: []
