---

- name: acme_sh account - Set default CA
  become: true
  ansible.builtin.command:
    cmd: >-
      /root/.acme.sh/acme.sh
      --set-default-ca
      --server {{ acme_sh_ca }}
  register: _acme_sh_set_ca
  changed_when: "'Changed' in _acme_sh_set_ca.stdout"

- name: acme_sh account - Register account with EAB
  become: true
  ansible.builtin.command:
    cmd: >-
      /root/.acme.sh/acme.sh
      --register-account
      --server {{ acme_sh_ca }}
      --eab
      --kid     {{ acme_sh_eab_kid }}
      --hmackey {{ acme_sh_eab_hmac_key }}
  register: _acme_sh_register
  changed_when: "'Registered' in _acme_sh_register.stdout"
  no_log: true
  when: acme_sh_eab_enabled
