---
- name: member - fail if required variables are unset
  ansible.builtin.fail:
    msg: "proxmox_pool_poolid and a non-empty proxmox_pool_members list are required."
  when: not proxmox_pool_poolid or proxmox_pool_members | length == 0

- name: member - manage pool membership
  community.proxmox.proxmox_pool_member:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    poolid:     "{{ proxmox_pool_poolid }}"
    members:    "{{ proxmox_pool_members }}"
    state:      "{{ proxmox_pool_member_state }}"
    exclusive:  "{{ proxmox_pool_exclusive }}"
    allow_move: "{{ proxmox_pool_allow_move }}"
  delegate_to: localhost
