---
- name: apply - fail if required variable is unset
  ansible.builtin.fail:
    msg: "proxmox_network_apply_node is required."
  when: not proxmox_network_apply_node

- name: apply - check for pending network changes
  community.proxmox.proxmox_node_network_info:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password }}"
    api_token_id:     "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    node: "{{ proxmox_network_apply_node }}"
    check_changes: true
  register: proxmox_network_pending
  delegate_to: localhost

- name: apply - apply staged network changes
  community.proxmox.proxmox_node_network:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password }}"
    api_token_id:     "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    node: "{{ proxmox_network_apply_node }}"
    state: apply
  when: proxmox_network_pending.has_pending_changes
  delegate_to: localhost
