---
- name: info - fail if required variable is unset
  ansible.builtin.fail:
    msg: "proxmox_network_info_node is required."
  when: not proxmox_network_info_node

- name: info - query live node network interfaces
  community.proxmox.proxmox_node_network_info:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    node:       "{{ proxmox_network_info_node }}"
    iface:      "{{ proxmox_network_info_iface | default(omit, true) }}"
    iface_type: "{{ proxmox_network_info_iface_type | default(omit, true) }}"
  register: proxmox_network_facts
  when: not proxmox_network_info_check_changes | bool
  delegate_to: localhost

- name: info - check for pending (unapplied) network changes
  community.proxmox.proxmox_node_network_info:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    node: "{{ proxmox_network_info_node }}"
    check_changes: true
  register: proxmox_network_pending_facts
  when: proxmox_network_info_check_changes | bool
  delegate_to: localhost
