---
# tasks file for etc_hosts

- name: debug
  debug:
    msg: >-
      {{
        groups | dict2items | rejectattr('key', 'in', ['all', 'ungrouped']) | map(attribute='value') | flatten | unique | list
      }}

# Use the hosts defined in the playbook itself
- name: Find the group used in the play
  set_fact:
    cluster_group: >-
      {{ groups
        | dict2items
        | selectattr('value', 'equalto', play_hosts)
        | map(attribute='key')
        | select('match', '^(?!all$|ungrouped$).*')
        | list
        | first
      }}


- name: Remove old /etc/hosts entries for group "{{ cluster_group }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '.*\s{{ item }}(\s|$)'
    state: absent
    backup: yes
  loop: "{{ groups[cluster_group] }}"


#------------------------------
# Used to set when part of cluster
#------------------------------
- name: Add "{{ cluster_group }}" cluster nodes to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "#  {mark} ANSIBLE MANAGED {{ cluster_group | upper }} NODES"
    block:  "{{ lookup('template', 'etc_hosts_cluster.j2') }}"
    backup: yes
  
