---

- name: lvm2 install - Update apt cache (Debian)
  ansible.builtin.apt:
    update_cache:      true
    cache_valid_time:  3600
  when: ansible_facts['os_family'] == 'Debian'

- name: lvm2 install - Install lvm2
  ansible.builtin.package:
    name:  lvm2
    state: present
