---

# ============================
# ============================
# Extending LVM
# note: vg will default to the OS VG unless given
# note: state is 'present' unless specifically given
# note: fs will be resized unless specifically given
# note: shrink is default to false unless specifically given
- name: LVM2 - lvchecks - Expand existing LV
  community.general.lvol:
    vg:       "{{ item.vg | default(os_vgs) }}"
    lv:       "{{ item.lv }}"
    size:     "{{ item.size }}"
    state:    "{{ item.state | default('present') }}"
    resizefs: "{{ item.resizefs | default('true') }}"
    shrink:   "{{ item.shrink | default('false') }}"
  loop:  "{{ lvm_settings }}"
