---

# =================================
# =================================
# returns a space separated list of available block devices
#   not associated with an FS, mounted, or has partitions
# will contain partitions if not associated as mentioned
- name: LVM2 - vgchecks - Finding available block devices
  ansible.builtin.shell: |
    # find available block  devices for use with LVM2
    RM_BLK_ITEM=
    BLK_LIST=$(lsblk -f -l --noheadings)
    JUST_DEVS=$(echo "$BLK_LIST" | awk '{print $1}')
    for item in $JUST_DEVS; do 
      if [[ $(echo $JUST_DEVS | grep "${item}p" ) ]]; then 
        RM_BLK_ITEM+="$item
    "; 
      fi;
    done
    RM_BLK_ITEM+=$(echo "$BLK_LIST" | awk 'NF > 1 {print $1}')
    for remove in $RM_BLK_ITEM; do
      JUST_DEVS=$(echo $JUST_DEVS | sed "s/$remove//")
    done
    echo $JUST_DEVS
  register: lvm_block_devices_output

# =================================
# =================================
- name:  LVM2 - vgchecks - making a list of available block devices
  ansible.builtin.set_fact:
    lvm_block_devices: "{{ lvm_block_devices_output.stdout.split() }}"
  when: 'lvm_block_devices_output is defined'

# =================================
# =================================
# expand an existing VG
- name: LVM2 - vgchecks - Create or extend a VG
  community.general.lvg:
    vg:  "{{ item.vg | default(os_vgs) }}"
    pvs: "{{ item.ondisk | default(lvm_block_devices) | map('regex_replace', '^', '/dev/') | list }}"
  loop:  
  - "{{ lvm_settings }}"
  when:  "item.vg is defined and not item.vg in ansible_facts.lvm.vgs"

