---
- name: info - query backup jobs / per-VM backup membership
  community.proxmox.proxmox_backup_info:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    vm_name:     "{{ proxmox_backup_info_vm_name | default(omit, true) }}"
    vm_id:       "{{ proxmox_backup_info_vm_id | default(omit, true) }}"
    backup_jobs: "{{ proxmox_backup_info_jobs }}"
  register: proxmox_backup_facts
  delegate_to: localhost
