---

- name: podman main - Install (Debian)
  import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: podman main - Install (RedHat)
  import_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: podman main - Enable podman socket
  ansible.builtin.systemd_service:
    name:    podman.socket
    state:   started
    enabled: true
