---
- name: info - fail if the chosen level's identifier is unset
  ansible.builtin.fail:
    msg: >
      proxmox_firewall_info_level requires a matching identifier:
      proxmox_firewall_info_node for 'node', proxmox_firewall_info_vmid for
      'vm', proxmox_firewall_info_vnet for 'vnet', proxmox_firewall_info_group
      for 'group'.
  when: >
    (proxmox_firewall_info_level == 'node' and not proxmox_firewall_info_node) or
    (proxmox_firewall_info_level == 'vm' and not proxmox_firewall_info_vmid) or
    (proxmox_firewall_info_level == 'vnet' and not proxmox_firewall_info_vnet) or
    (proxmox_firewall_info_level == 'group' and not proxmox_firewall_info_group)

- name: info - query firewall rules/groups/aliases/ipsets
  community.proxmox.proxmox_firewall_info:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    level: "{{ proxmox_firewall_info_level }}"
    node:  "{{ proxmox_firewall_info_node | default(omit, true) }}"
    vmid:  "{{ proxmox_firewall_info_vmid | default(omit, true) }}"
    vnet:  "{{ proxmox_firewall_info_vnet | default(omit, true) }}"
    group: "{{ proxmox_firewall_info_group | default(omit, true) }}"
  register: proxmox_firewall_facts
  delegate_to: localhost

- name: info - query node-level firewall options
  community.proxmox.proxmox_node_firewall_options_info:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    node_name: "{{ proxmox_firewall_info_node_options_target }}"
  register: proxmox_firewall_node_options_facts
  when: proxmox_firewall_info_node_options_target | length > 0
  delegate_to: localhost
