---
galaxy_info:
  author: mgcdrd
  description: Manage ProxMox VE node power state, certificates/DNS/subscription config, and task monitoring via the PVE API
  role_name: proxmox_node

  license: GPL-3.0-or-later
  min_ansible_version: '2.14'

  galaxy_tags:
    - mgcdrd

collections:
  - community.proxmox
