---

# ================
# 
- name: ssl_scripting main - Creating base directory
  ansible.builtin.file:
    path: "{{ ssl_scripting.base_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: ssl_scripting main - Pushing make_new_ssl.sh template
  ansible.builtin.template:
    src:  make_new_ssl.sh.j2
    dest: "{{ ssl_scripting.base_dir }}/make_new_ssl.sh"
    owner: root
    group: root
    mode:  '0750'

- name: ssl_scriping main - Checking for presence of dummy key
  ansible.builtin.stat:
    path:  "{{ ssl_scripting.base_dir }}/ssl-dummy.key"
  register:  ssl_scripting_dummy_key

- name: ssl_scriping main - Checking for presence of dummy crt
  ansible.builtin.stat:
    path:  "{{ ssl_scripting.base_dir }}/ssl-dummy.crt"
  register:  ssl_scripting_dummy_crt

- name: ssl_scripting main - Checking for dhparam.crt
  ansible.builtin.stat:
    path:  "{{ ssl_scripting.base_dir }}/dhparam.pem"
  register: ssl_scripting_dhparam

- name: ssl_scripting main - Create dummy key
  ansible.builtin.shell:
    cmd: "{{ ssl_scripting.base_dir }}/make_new_ssl.sh ssl-dummy"
  when: not ssl_scripting_dummy_key.stat.exists

- name: ssl_scripting main - Create dummy crt
  ansible.builtin.shell:
    cmd: "openssl x509 -req -days 365 -in {{ ssl_scripting.base_dir }}/extras/ssl-dummy.csr -signkey {{ ssl_scripting.base_dir }}/ssl-dummy.key -out {{ ssl_scripting.base_dir }}/ssl-dummy.crt"
  when: not ssl_scripting_dummy_crt.stat.exists

- name: ssl_scripting main - Create dhparam
  ansible.builtin.shell:
    cmd:  "openssl dhparam -out {{ ssl_scripting.base_dir }}/dhparam.pem {{ ssl_scripting.def_bits }}"
  when: not ssl_scripting_dhparam.stat.exists
