---
galaxy_info:
  author: mgcdrd
  description: Manage ProxMox VE-integrated Ceph daemons (mon/mgr/mds), OSDs, and pools via the PVE API
  role_name: proxmox_ceph

  license: GPL-3.0-or-later
  min_ansible_version: '2.14'

  galaxy_tags:
    - mgcdrd

collections:
  - community.proxmox
