---
galaxy_info:
  author: mgcdrd
  description: Create/delete ProxMox VE resource pools and manage VM/storage pool membership via the PVE API
  role_name: proxmox_pool

  license: GPL-3.0-or-later
  min_ansible_version: '2.14'

  galaxy_tags:
    - mgcdrd

collections:
  - community.proxmox
