---
galaxy_info:
  author: mgcdrd
  description: Create, delete, and roll back ProxMox VE VM/CT snapshots via the PVE API
  role_name: proxmox_snapshot

  license: GPL-3.0-or-later
  min_ansible_version: '2.14'

  galaxy_tags:
    - mgcdrd

collections:
  - community.proxmox
