---
- name: clone - fail if required variables are unset
  ansible.builtin.fail:
    msg: "proxmox_lxc_clone_source_name and proxmox_lxc_clone_hostname are required."
  when: not proxmox_lxc_clone_source_name or not proxmox_lxc_clone_hostname

- name: clone - discover source container
  ansible.builtin.include_tasks: discover.yml
  vars:
    proxmox_lxc_discover_name: "{{ proxmox_lxc_clone_source_name }}"

- name: clone - clone container
  community.proxmox.proxmox:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    vmid:       "{{ proxmox_lxc_clone_vmid | default(omit, true) }}"
    node:       "{{ proxmox_lxc_clone_node | default(proxmox_lxc_discovered_node, true) }}"
    hostname:   "{{ proxmox_lxc_clone_hostname }}"
    clone:      "{{ proxmox_lxc_discovered_vmid }}"
    clone_type: "{{ proxmox_lxc_clone_type }}"
    storage:    "{{ proxmox_lxc_clone_storage | default(omit, true) }}"
    timeout:    "{{ proxmox_lxc_clone_timeout }}"
  register: proxmox_lxc_clone_result
  delegate_to: localhost

- name: clone - start container
  community.proxmox.proxmox:
    api_host:         "{{ proxmox_api_host }}"
    api_user:         "{{ proxmox_api_user }}"
    api_password:     "{{ proxmox_api_password | default(omit) }}"
    api_token_id:     "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs:   "{{ proxmox_validate_certs }}"
    hostname: "{{ proxmox_lxc_clone_hostname }}"
    state: started
  when: proxmox_lxc_clone_start_after | bool
  delegate_to: localhost
