---

- name: docker main - Install (Debian)
  import_tasks: install-debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: docker main - Install (RedHat)
  import_tasks: install-redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: docker main - Configure default logging driver
  ansible.builtin.template:
    src:   daemon.json.j2
    dest:  /etc/docker/daemon.json
    owner: root
    group: root
    mode:  "0644"
  notify: docker restart

- name: docker main - Enable and start docker service
  ansible.builtin.systemd_service:
    name:         docker.service
    state:        started
    enabled:      true
    daemon_reload: true
