---

- name: docker main - Install (Debian)
  import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: docker main - Install (RedHat)
  import_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: docker main - Enable and start docker service
  ansible.builtin.systemd_service:
    name:         docker.service
    state:        started
    enabled:      true
    daemon_reload: true
