---
- name: info - list ACME account names
  community.proxmox.proxmox_acme_accounts_info:
    api_host:       "{{ proxmox_acme_api_host }}"
    api_user:       "{{ proxmox_acme_api_user }}"
    api_password:   "{{ proxmox_acme_api_password }}"
    validate_certs: "{{ proxmox_acme_validate_certs }}"
  register: proxmox_acme_accounts_facts
  delegate_to: localhost

- name: info - list ACME DNS challenge plugins
  community.proxmox.proxmox_acme_plugins_info:
    api_host:       "{{ proxmox_acme_api_host }}"
    api_user:       "{{ proxmox_acme_api_user }}"
    api_password:   "{{ proxmox_acme_api_password }}"
    validate_certs: "{{ proxmox_acme_validate_certs }}"
  register: proxmox_acme_plugins_facts
  delegate_to: localhost
