---

login_banner_text: |
  **************************************************************************
  *                                                                        *
  *  AUTHORIZED ACCESS ONLY. All activity is monitored and logged.        *
  *  Unauthorized access is prohibited and may be subject to prosecution. *
  *                                                                        *
  **************************************************************************
