---

- name: crypto-policies main - Install and enable crypto-policies
  ansible.builtin.import_tasks: install.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: crypto-policies main - Configure crypto-policies
  ansible.builtin.import_tasks: configure.yml
  when: ansible_facts['os_family'] == 'RedHat'